{
 "title": "IOT",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Gun Safe Gyroscope (GSG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "  from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gsgMotion\")"
    }
   ]
  },
  {
   "title": "Alarms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "  from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alarm\")"
    }
   ]
  },
  {
   "title": "DHT (Temperature & Humidity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "  from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"humidity\" or r[\"_measurement\"] == \"temperature\")"
    }
   ]
  },
  {
   "title": "Keypad input",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"keypadInput\")"
    }
   ]
  },
  {
   "title": "Buzzer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"buzzerStatus\")"
    }
   ]
  },
  {
   "title": "Door Sensor (Button)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"buttonStatus\")"
    }
   ]
  },
  {
   "title": "Door Ultrasonic Sensor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"UDSDistance\")"
    }
   ]
  },
  {
   "title": "Door Light (LED)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"LEDStatus\")"
    }
   ]
  },
  {
   "title": "PIR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "query": "from(bucket: \"smart_measurements\")\r\n  |> range(start: 0)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"PIRStatus\")\r\n"
    }
   ]
  }
 ]
}